# Ejercicio de modelo de datos
Con la libreria de scikitleran se realizara un ejercicio de modelado de datos. Implementando un modelo de regresion lineral y modelo de regresion multivariado

# Importacion de las librerias necesarias

In [1]:
#libreias
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

# Importacion de los datos

In [2]:
ruta = 'cleandata.xlsx'
df = pd.read_excel(ruta)

c:\Users\glopa\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

# Verifiacion dataframe

In [3]:
df.head()

,Retailer,Salerank,X2013USSales,X2013WorldSales,ProfitMargin,NumStores,Industry,Reward,ProgramName,RewardType,RewardStructure,RewardSize,ExpirationMonth,IndustryType
0,A&P,74,5.831,5.831,48.85,0.277,"Discount, Variety Stores",0,No rewards program,-,-,-,-,Discount
1,Albertsons,21,19.452,19.452,69.02,1.024,Grocery Stores,0,No rewards program,-,-,-,-,Grocery
2,Aldi,38,10.898,10.650,69.41,1.328,Grocery Stores,0,No rewards program,-,-,-,-,Grocery
3,Alimentation Couche Tard (Circle K),82,4.755,8.551,68.03,3.826,Grocery Stores,0,No rewards program,-,-,-,-,Grocery
4,Apple Stores,15,26.648,30.736,11.07,0.254,ElectronicEquipment,0,No rewards program,-,-,-,-,Specialty

In [4]:
#informacion del dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Retailer         100 non-null    str
 1   Salerank         100 non-null    int64
 2   X2013USSales     100 non-null    float64
 3   X2013WorldSales  100 non-null    float64
 4   ProfitMargin     100 non-null    float64
 5   NumStores        100 non-null    float64
 6   Industry         100 non-null    str
 7   Reward           100 non-null    int64
 8   ProgramName      100 non-null    str
 9   RewardType       96 non-null     str
 10  RewardStructure  100 non-null    str
 11  RewardSize       100 non-null    object
 12  ExpirationMonth  100 non-null    object
 13  IndustryType     100 non-null    str
dtypes: float64(4), int64(2), object(2), str(6)
memory usage: 11.1+ KB

In [5]:
#descripcion estadistica del dataset
df.describe()

,Salerank,X2013USSales,X2013WorldSales,ProfitMargin,NumStores,Reward
count,100.000000,100.000000,100.000000,100.00000,100.000000,100.00
mean,50.500000,18.373500,24.131540,45.27300,2.698760,0.55
std,29.011492,36.476003,50.845864,29.23139,3.997641,0.50
min,1.000000,3.600000,3.600000,1.02000,0.000000,0.00
25%,25.750000,5.206750,6.108250,19.44500,0.338500,0.00
50%,50.500000,8.348500,9.629000,42.02000,1.331500,1.00
75%,75.250000,16.841000,22.131500,69.57250,3.519750,1.00
max,100.000000,334.302000,473.979000,99.20000,26.644000,1.00

In [6]:
#Descripcion incluyendo variables categoricas
df.describe(include=['object','str'])

,Retailer,Industry,ProgramName,RewardType,RewardStructure,RewardSize,ExpirationMonth,IndustryType
count,100,100,100,96,100,100,100,100
unique,100,17,58,11,57,27,11,5
top,A&P,"Discount, Variety Stores",No rewards program,-,-,-,-,Specialty
freq,1,18,40,37,41,44,44,43

# Limpiea de datos y transforamcion de datos

In [7]:
# se filtran los datos los cuales no tengan reward y que no tengan tiendas
df_clean_1= df[df['Reward'] != 0]
df_clean_1= df_clean_1[df['NumStores'] != 0]
df_clean_1.describe()

C:\Users\glopa\AppData\Local\Temp\ipykernel_15712\2415360955.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_clean_1= df_clean_1[df['NumStores'] != 0]

,Salerank,X2013USSales,X2013WorldSales,ProfitMargin,NumStores,Reward
count,53.000000,53.000000,53.000000,53.000000,53.000000,53.0
mean,51.075472,15.562830,19.428717,47.394151,2.784434,1.0
std,29.479360,18.919833,22.414025,28.352150,4.250738,0.0
min,2.000000,3.600000,3.600000,1.990000,0.085000,1.0
25%,27.000000,5.165000,6.077000,23.470000,0.420000,1.0
50%,47.000000,8.883000,10.205000,43.170000,1.335000,1.0
75%,77.000000,16.330000,19.031000,71.560000,3.854000,1.0
max,100.000000,93.598000,93.598000,99.200000,26.644000,1.0

In [8]:
# elimar las columnas donde el mes de expiracion sea 999 
df_clean_2 = df_clean_1[df_clean_1['ExpirationMonth'] != 999]
df_clean_2.describe()

,Salerank,X2013USSales,X2013WorldSales,ProfitMargin,NumStores,Reward
count,46.000000,46.000000,46.000000,46.000000,46.000000,46.0
mean,48.326087,16.954696,21.167283,46.345652,2.782370,1.0
std,29.768779,19.944292,23.550197,28.117501,4.384017,0.0
min,2.000000,3.600000,3.600000,1.990000,0.085000,1.0
25%,23.000000,6.134000,6.268750,23.245000,0.476000,1.0
50%,43.500000,9.218000,10.994500,43.695000,1.322000,1.0
75%,69.750000,18.428250,24.394500,68.640000,3.770250,1.0
max,100.000000,93.598000,93.598000,99.200000,26.644000,1.0

In [9]:
variables_categoricas = ['Industry','ProgramName','RewardType','RewardStructure','RewardSize','ExpirationMonth','IndustryType']
for var in variables_categoricas:
    print(f'variable: {var}')
    print(df_clean_2[var].unique())

variable: Industry
<StringArray>
['Discount, Variety Stores',        'Auto Parts Stores',
           'Grocery Stores',           'Apparel Stores',
       'Electronics Stores',              'Restaurants',
              'Drug Stores',    'Sporting Goods Stores',
        'Department Stores',  'Specialty Retail, Other',
  'Home Improvement Stores']
Length: 11, dtype: str
variable: ProgramName
<StringArray>
[                      '7REWARDS',                     'SpeedPerks',
          'Stop and Shop Rewards',                 'PerfectRewards',
               'AutoZone Rewards',                    'My Best Buy',
                      'Fuelperks',                  'My BJ's Perks',
                   'Dine Rewards',             'My Chili's Rewards',
                     'ExtraBucks',                       'eRewards',
          'Dillard's Credit Card',                 'PowerUpRewards',
            'GAP Rewards Program', 'InStore Rewards / Fuel Rewards',
            'Points Club Rewards',                      'FuelSaver',
                    'Fuel Reward',               'JCPenney Rewards',
               'Yes2You Rewards ',                   'Fuel Program',
         'Love Your Body Program',                         'mPerks',
                       'InCircle',              'Nordstrom Rewards',
                  'Choice Member',                      'O'Rewards',
                     'AdvantEdge',                     'Wellness+ ',
                  'Reward Points',                      'SaveSmart',
          'Shop Your Way Rewards',                'Instant Rewards',
                'Staples Rewards',           'My Starbucks Rewards',
    'SUBWAY Card Rewards Program',                 'My Cub Rewards',
                   'Fuel Rewards',              'Reward The Public',
                  'Rewards"R" Us',                'Neighbor's Club',
              'TrueValue Rewards',                'Balance Rewards']
Length: 44, dtype: str
variable: RewardType
<StringArray>
[                     'store credit',                      'gas discount',
                  'free merchandise',                                 nan,
 'store credit  and various rewards',                      'free product']
Length: 6, dtype: str
variable: RewardStructure
<StringArray>
[                                                                                                              'Buy 6 drinks  =  free drink',
                                                                               'Spend $30/$100 = $5/$20 rewards for the next $10+ purchase ',
                                                      'Spend $100 and earn 0.10 off per gallon for the maximum discount of $2.20 per gallon',
                                                                                   'Spend $400 earn 2,000 points = $20 PERFECT REWARDS card',
                                                                                'Spend $20+ 5 times earn 5 credits = $20 merchandise credit',
                                                                                        'Spend $250 earn 250 points = $5 reward certificate',
                                                                                        'Spend $50  = $.05 off per gallon, up to 20 gallons',
                                                                                                 '2% of purchase amount for future purchase',
                                                                      'Spend $20 X3 = 50% off next check, capped at $20 (assumes $30 check)',
                                                                              'Spend $80/160 earn 80/160 points = $8/$16 appetizer / entree',
                                                    '2% off for future purchase except alcohol, prescriptions, stamps, and tabacoo products',
                                                                             'Spend $300 earn 300 points = $10 rewards off future purchases',
                                                                                     'Spend $750 earn 1,500 points = $10 reward certificate',
                                'Spend $6,000/$3,000 on new games/pre-owned games earn 60,000 points =$60 PS4 DualShock Wireless Controller',
                                                                  'Spend $200 earn 1,000 points = $5 reward certificate for future purchase',
                                                                                                           'Spend $50 = $.10 off per gallon',
                                                            'Buy 7.5 whole sub = 1 free sub / Spend $50+  = $10 discount off a $50 gas card',
                                                                 'Spend $66.7 earn 1,000 points = $1 reward certificate for future purchase',
                                                                   'Buy $3/$6 grocery and earn $0.03/$0.06 off per gallon, up to 20 gallons',
                                                                                          'Spend $100 earn 100 points = $.05 off per gallon',
                                                                   'Spend $100 earn 100 points = $10 reward certificate for future purchase',
                                                                    'Spend $100 earn 100 points = $5 reward certificate for future purchase',
                                                                        'Spend $100 earn 100 points = $.10 off per gallon, up to 35 gallons',
                                     'Spend $80 earn 4 points = $15 off future purchase, Spend $160 earn 8 points = $25 off future purchase',
                                                                               'Spend $100 to get $10 off next purchase (for baby products)',
                                                              'Spend $5,000 earn 10,00 points = $100 reward certificate for future purchase',
                                                               'Spend $1,000 earn 2,000 points = $20 reward certificate for future purchase',
                                                                                'Get 10% discount in rewards for shopping paper, ink, toner',
                                                                                        'Spend $150  earn 150 points = $5 O'Rewards coupon ',
                                                                                                     'Spend $100 for $0.10 up to 20 gallons',
                                                                                                    'Spend $250  = 10% off future purchases',
                                                                               'Spend $100 and earn 0.10 off per gallon for a single fillup',
                                                                                         'Spend $100 earn 100 points = $1.1 worth of coupon',
                                                                                       'Spend $100 earn 1000 points = $1 reward certificate',
                                                                                                       'Spend $300 = $100 off next purchase',
                                                                                              '2% or 5% on everything except postage stamps',
                                                                                             'Buy 12 drinks to earn 12 stars  =  free drink',
                                                                  'Spend $1 earn 1 point = various rewards (e.g., 75 pts for footlong subs)',
                                                                                                          'Spend $50  = $.05 off per gallon',
 'Spend $100/$1,000/$2,000/$4,000 earn 100/1,000/2,000/4,000 points = $.10/$1.00/$2.00/$4.00 off per gallon at participating Shell stations',
                                                                 'Spend $200 earn 1,000 points = $10 reward certificate for future purchase',
                                                                                    'Spend $125 earn $5 Reward Dollars for future purchases',
                                                                    'Spend $150 X3 times earn seasonal (quarterly) reward ($5 store credit)',
                                                                  'Spend $250 earn 2,500 points = $5 reward certificate for future purchase',
                                          '500 points on every prescription filled in the pharmacy, good for $5 discount of future purchase']
Length: 45, dtype: str
variable: RewardSize
[16.67 16.6 15 5 20 2 1.5 22.22 10 3.3 1.33 1 2.5 4 13.3 16 3.33 1.1 33.33
 3.5 8 6.7 1.11]
variable: ExpirationMonth
[12 2 1 3 6 4 1.5 24 36]
variable: IndustryType
<StringArray>
['Discount', 'Specialty', 'Grocery', 'Restaurants', 'Department']
Length: 5, dtype: str

In [10]:
# Convertir la columna Expiration y RewardSize a tipo de dato int y float respectivamente
df_clean_2['ExpirationMonth'] = df_clean_2['ExpirationMonth'].astype(int)
df_clean_2['RewardSize'] = df_clean_2['RewardSize'].astype(float)
df_clean_2.describe()

,Salerank,X2013USSales,X2013WorldSales,ProfitMargin,NumStores,Reward,RewardSize,ExpirationMonth
count,46.000000,46.000000,46.000000,46.000000,46.000000,46.0,46.000000,46.000000
mean,48.326087,16.954696,21.167283,46.345652,2.782370,1.0,6.923696,7.282609
std,29.768779,19.944292,23.550197,28.117501,4.384017,0.0,7.215197,7.762196
min,2.000000,3.600000,3.600000,1.990000,0.085000,1.0,1.000000,1.000000
25%,23.000000,6.134000,6.268750,23.245000,0.476000,1.0,2.000000,1.250000
50%,43.500000,9.218000,10.994500,43.695000,1.322000,1.0,3.750000,3.000000
75%,69.750000,18.428250,24.394500,68.640000,3.770250,1.0,10.000000,12.000000
max,100.000000,93.598000,93.598000,99.200000,26.644000,1.0,33.330000,36.000000

In [11]:
# dataset final para el modelado
df_cleaned = df_clean_2[[ 'Salerank', 'X2013USSales', 'X2013WorldSales', 'ProfitMargin', 'NumStores', 'Reward', 'RewardSize', 'ExpirationMonth' ]]

# Exploracion de los datos 
En este caso solo vamos a calcular la correlacion

In [12]:
# Calcular correlacion 
df_cleaned.corr()['ExpirationMonth'].sort_values(ascending=False)

ExpirationMonth    1.000000
NumStores          0.501835
X2013WorldSales   -0.073057
X2013USSales      -0.094228
ProfitMargin      -0.096278
RewardSize        -0.142806
Salerank          -0.248431
Reward                  NaN
Name: ExpirationMonth, dtype: float64

# Modelado regresion lineal simple

In [13]:
# importacion modelo de regresion lineal 
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

In [14]:
df_cleaned.info()

<class 'pandas.DataFrame'>
Index: 46 entries, 45 to 98
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Salerank         46 non-null     int64
 1   X2013USSales     46 non-null     float64
 2   X2013WorldSales  46 non-null     float64
 3   ProfitMargin     46 non-null     float64
 4   NumStores        46 non-null     float64
 5   Reward           46 non-null     int64
 6   RewardSize       46 non-null     float64
 7   ExpirationMonth  46 non-null     int64
dtypes: float64(5), int64(3)
memory usage: 3.2 KB

In [15]:
# Desplegar el modelo identificando la  mejor variable predictora para la variable objetivo ExpirationMonth
predictores =['Salerank', 'X2013USSales', 'X2013WorldSales', 'ProfitMargin', 'NumStores', 'Reward', 'RewardSize']
y = df_cleaned['ExpirationMonth']
for col in predictores:
    X = df_cleaned[[col]]
    Lm= LinearRegression()
    Lm.fit(X, y)
    y_pred = Lm.predict(X)
    r2 = r2_score(y, y_pred)
    print(f'predictores: {col}, R2: {r2}')

predictores: Salerank, R2: 0.06171815231609046
predictores: X2013USSales, R2: 0.008878861590729259
predictores: X2013WorldSales, R2: 0.005337319364168258
predictores: ProfitMargin, R2: 0.009269408773271204
predictores: NumStores, R2: 0.25183847474426735
predictores: Reward, R2: 0.0
predictores: RewardSize, R2: 0.020393530225667922

### Modelo con la variable predictora que escogimos

In [16]:
# Modelado y transformacion de la variable predictora NumStores
x=df_cleaned[['NumStores']]
y=df_cleaned['ExpirationMonth']
constructor=LinearRegression()
constructor.fit(x,y)
y_pred=constructor.predict(x)
r2=r2_score(y,y_pred)
intercepto=constructor.intercept_
coeficiente=constructor.coef_
print(f'R2: {r2}, Intercepto: {intercepto}, Coeficiente: {coeficiente}')

R2: 0.25183847474426735, Intercepto: 4.810382363374464, Coeficiente: [0.8885327]

### modelo con la misma variable, aplicando logaritmo a la variable objetivo

In [17]:
y = np.log(df_cleaned['ExpirationMonth'])
constructor=LinearRegression()
constructor.fit(x,y)
y_pred=constructor.predict(x)
r2=r2_score(y,y_pred)
intercepto=constructor.intercept_
coeficiente=constructor.coef_
print(f'R2: {r2}, Intercepto: {intercepto}, Coeficiente: {coeficiente}')

R2: 0.06581331461672801, Intercepto: 1.2329487168966393, Coeficiente: [0.06574924]

### modelo con la misma variable, aplicando logaritmo a la variable predictora

In [18]:
x=np.log(df_cleaned[['NumStores']])
y = df_cleaned['ExpirationMonth']
constructor=LinearRegression()
constructor.fit(x,y)
y_pred=constructor.predict(x)
r2=r2_score(y,y_pred)
intercepto=constructor.intercept_
coeficiente=constructor.coef_
print(f'R2: {r2}, Intercepto: {intercepto}, Coeficiente: {coeficiente}')

R2: 0.14402359025105027, Intercepto: 6.764410211838508, Coeficiente: [2.2326292]

### modelo con la misma variable, aplicando logaritmo a las dos variables

In [19]:
x=np.log(df_cleaned[['NumStores']])
y = np.log(df_cleaned['ExpirationMonth'])
constructor=LinearRegression()
constructor.fit(x,y)
y_pred=constructor.predict(x)
r2=r2_score(y,y_pred)
intercepto=constructor.intercept_
coeficiente=constructor.coef_
print(f'R2: {r2}, Intercepto: {intercepto}, Coeficiente: {coeficiente}')

R2: 0.06288558582164738, Intercepto: 1.366322268003322, Coeficiente: [0.21354866]